---
- src: git@github.com:gilyazov-ranel/vector-role.git
  scm: git
  name: vector-role

- src: git@github.com:gilyazov-ranel/lighthouse-role.git
  scm: git
  name: lighthouse-role

- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse 

